config.action_mailer.smtp_settings = {
  :enable_starttls_auto => true,
  :address => "smtp.gmail.com",
  :port => 587,
  :domain => 'smtp.gmail.com',
  :user_name =>  <%= ENV['MAIL_USERNAME'] %>, #gmailアドレス
  :password => <%= ENV['MAIL_PASS'] %>, #gmailパスワード
  :authentication => 'login',
}